In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

In [2]:
df=pd.read_excel('C:\Users\user\Downloads\loan_approval_dataset.xlsx')
df

loan_id   no_of_dependents      education  self_employed   income_annum  \
0           1                  2       Graduate             No        9600000   
1           2                  0   Not Graduate            Yes        4100000   
2           3                  3       Graduate             No        9100000   
3           4                  3       Graduate             No        8200000   
4           5                  5   Not Graduate            Yes        9800000   
...       ...                ...            ...            ...            ...   
4264     4265                  5       Graduate            Yes        1000000   
4265     4266                  0   Not Graduate            Yes        3300000   
4266     4267                  2   Not Graduate             No        6500000   
4267     4268                  1   Not Graduate             No        4100000   
4268     4269                  1       Graduate             No        9200000   

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000   
1         12200000           8           417                    2700000   
2         29700000          20           506                    7100000   
3         30700000           8           467                   18200000   
4         24200000          20           382                   12400000   
...            ...         ...           ...                        ...   
4264       2300000          12           317                    2800000   
4265      11300000          20           559                    4200000   
4266      23900000          18           457                    1200000   
4267      12800000           8           780                    8200000   
4268      29700000          10           607                   17800000   

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000   
1                      2200000               8800000            3300000   
2                      4500000              33300000           12800000   
3                      3300000              23300000            7900000   
4                      8200000              29400000            5000000   
...                        ...                   ...                ...   
4264                    500000               3300000             800000   
4265                   2900000              11000000            1900000   
4266                  12400000              18100000            7300000   
4267                    700000              14100000            5800000   
4268                  11800000              35700000           12000000   

      loan_status  
0        Approved  
1        Rejected  
2        Rejected  
3        Rejected  
4        Rejected  
...           ...  
4264     Rejected  
4265     Approved  
4266     Rejected  
4267     Approved  
4268     Approved  

[4269 rows x 13 columns]

In [3]:
df.head()

loan_id   no_of_dependents      education  self_employed   income_annum  \
0        1                  2       Graduate             No        9600000   
1        2                  0   Not Graduate            Yes        4100000   
2        3                  3       Graduate             No        9100000   
3        4                  3       Graduate             No        8200000   
4        5                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   loan_id                    4269 non-null   int64 
 1    no_of_dependents          4269 non-null   int64 
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64 
 5    loan_amount               4269 non-null   int64 
 6    loan_term                 4269 non-null   int64 
 7    cibil_score               4269 non-null   int64 
 8    residential_assets_value  4269 non-null   int64 
 9    commercial_assets_value   4269 non-null   int64 
 10   luxury_assets_value       4269 non-null   int64 
 11   bank_asset_value          4269 non-null   int64 
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB


In [5]:
df.isnull()

loan_id   no_of_dependents   education   self_employed   income_annum  \
0       False              False       False           False          False   
1       False              False       False           False          False   
2       False              False       False           False          False   
3       False              False       False           False          False   
4       False              False       False           False          False   
...       ...                ...         ...             ...            ...   
4264    False              False       False           False          False   
4265    False              False       False           False          False   
4266    False              False       False           False          False   
4267    False              False       False           False          False   
4268    False              False       False           False          False   

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0            False       False         False                      False   
1            False       False         False                      False   
2            False       False         False                      False   
3            False       False         False                      False   
4            False       False         False                      False   
...            ...         ...           ...                        ...   
4264         False       False         False                      False   
4265         False       False         False                      False   
4266         False       False         False                      False   
4267         False       False         False                      False   
4268         False       False         False                      False   

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                        False                 False              False   
1                        False                 False              False   
2                        False                 False              False   
3                        False                 False              False   
4                        False                 False              False   
...                        ...                   ...                ...   
4264                     False                 False              False   
4265                     False                 False              False   
4266                     False                 False              False   
4267                     False                 False              False   
4268                     False                 False              False   

       loan_status  
0            False  
1            False  
2            False  
3            False  
4            False  
...            ...  
4264         False  
4265         False  
4266         False  
4267         False  
4268         False  

[4269 rows x 13 columns]

In [6]:
df.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [7]:
df.head()

loan_id   no_of_dependents      education  self_employed   income_annum  \
0        1                  2       Graduate             No        9600000   
1        2                  0   Not Graduate            Yes        4100000   
2        3                  3       Graduate             No        9100000   
3        4                  3       Graduate             No        8200000   
4        5                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [8]:
df.drop(["loan_id"],axis=1,inplace=True)
df.head()

no_of_dependents      education  self_employed   income_annum  \
0                  2       Graduate             No        9600000   
1                  0   Not Graduate            Yes        4100000   
2                  3       Graduate             No        9100000   
3                  3       Graduate             No        8200000   
4                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [9]:
df.iloc[:,np.r_[0:11]]

no_of_dependents      education  self_employed   income_annum  \
0                     2       Graduate             No        9600000   
1                     0   Not Graduate            Yes        4100000   
2                     3       Graduate             No        9100000   
3                     3       Graduate             No        8200000   
4                     5   Not Graduate            Yes        9800000   
...                 ...            ...            ...            ...   
4264                  5       Graduate            Yes        1000000   
4265                  0   Not Graduate            Yes        3300000   
4266                  2   Not Graduate             No        6500000   
4267                  1   Not Graduate             No        4100000   
4268                  1       Graduate             No        9200000   

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000   
1         12200000           8           417                    2700000   
2         29700000          20           506                    7100000   
3         30700000           8           467                   18200000   
4         24200000          20           382                   12400000   
...            ...         ...           ...                        ...   
4264       2300000          12           317                    2800000   
4265      11300000          20           559                    4200000   
4266      23900000          18           457                    1200000   
4267      12800000           8           780                    8200000   
4268      29700000          10           607                   17800000   

       commercial_assets_value   luxury_assets_value   bank_asset_value  
0                     17600000              22700000            8000000  
1                      2200000               8800000            3300000  
2                      4500000              33300000           12800000  
3                      3300000              23300000            7900000  
4                      8200000              29400000            5000000  
...                        ...                   ...                ...  
4264                    500000               3300000             800000  
4265                   2900000              11000000            1900000  
4266                  12400000              18100000            7300000  
4267                    700000              14100000            5800000  
4268                  11800000              35700000           12000000  

[4269 rows x 11 columns]

In [10]:
df.iloc[:,11]

0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
          ...    
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
Name:  loan_status, Length: 4269, dtype: object

In [11]:
x=df.iloc[:,np.r_[0:11]].values
y=df.iloc[:,11].values

In [12]:
x

array([[2, ' Graduate', ' No', ..., 17600000, 22700000, 8000000],
       [0, ' Not Graduate', ' Yes', ..., 2200000, 8800000, 3300000],
       [3, ' Graduate', ' No', ..., 4500000, 33300000, 12800000],
       ...,
       [2, ' Not Graduate', ' No', ..., 12400000, 18100000, 7300000],
       [1, ' Not Graduate', ' No', ..., 700000, 14100000, 5800000],
       [1, ' Graduate', ' No', ..., 11800000, 35700000, 12000000]],
      dtype=object)

In [13]:
y

array([' Approved', ' Rejected', ' Rejected', ..., ' Rejected',
       ' Approved', ' Approved'], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

In [15]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
Labelencoder_s=LabelEncoder()
Labelencoder_n=LabelEncoder()

In [17]:
X_train

array([[2, ' Graduate', ' Yes', ..., 1700000, 9200000, 1700000],
       [1, ' Not Graduate', ' Yes', ..., 1000000, 25900000, 11100000],
       [2, ' Not Graduate', ' No', ..., 3100000, 23800000, 11800000],
       ...,
       [3, ' Not Graduate', ' Yes', ..., 10300000, 25300000, 7400000],
       [4, ' Not Graduate', ' No', ..., 2500000, 21000000, 6600000],
       [1, ' Not Graduate', ' Yes', ..., 7600000, 16000000, 3200000]],
      dtype=object)

In [18]:
X_train[:,0]

array([2, 1, 2, ..., 3, 4, 1], dtype=object)

In [19]:
X_train[:,0]=Labelencoder_s.fit_transform(X_train[:,0])

In [20]:
X_train[:,0]

array([2, 1, 2, ..., 3, 4, 1], dtype=object)

In [21]:
X_train[:,1]

array([' Graduate', ' Not Graduate', ' Not Graduate', ...,
       ' Not Graduate', ' Not Graduate', ' Not Graduate'], dtype=object)

In [22]:
X_train[:,1]=Labelencoder_s.fit_transform(X_train[:,1])
X_train[:,1]

array([0, 1, 1, ..., 1, 1, 1], dtype=object)

In [23]:
df.head()

no_of_dependents      education  self_employed   income_annum  \
0                  2       Graduate             No        9600000   
1                  0   Not Graduate            Yes        4100000   
2                  3       Graduate             No        9100000   
3                  3       Graduate             No        8200000   
4                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [24]:
X_train[:,2]=Labelencoder_n.fit_transform(X_train[:,2])
X_train[:,2]

array([1, 1, 0, ..., 1, 0, 1], dtype=object)

In [25]:
Labelencoder_y=LabelEncoder()
y_train=Labelencoder_y.fit_transform(y_train)

y_train

array([1, 1, 0, ..., 0, 0, 0])

In [26]:
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [27]:
X_test[:,0]=Labelencoder_s.fit_transform(X_test[:,0])
X_test[:,1]=Labelencoder_s.fit_transform(X_test[:,1])
X_test[:,2]=Labelencoder_n.fit_transform(X_test[:,2])


In [28]:
X_test

array([[1, 0, 1, ..., 5300000, 28700000, 4200000],
       [2, 0, 1, ..., 12200000, 17800000, 10800000],
       [1, 0, 0, ..., 3500000, 18700000, 8300000],
       ...,
       [0, 0, 1, ..., 4800000, 25400000, 11100000],
       [2, 1, 0, ..., 7800000, 10800000, 2400000],
       [0, 0, 1, ..., 200000, 17100000, 5200000]], dtype=object)

In [29]:
y_test=Labelencoder_y.fit_transform(y_test)

In [30]:
y_pred=model.predict(X_test)
y_pred


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7599531615925058

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0    no_of_dependents          4269 non-null   int64 
 1    education                 4269 non-null   object
 2    self_employed             4269 non-null   object
 3    income_annum              4269 non-null   int64 
 4    loan_amount               4269 non-null   int64 
 5    loan_term                 4269 non-null   int64 
 6    cibil_score               4269 non-null   int64 
 7    residential_assets_value  4269 non-null   int64 
 8    commercial_assets_value   4269 non-null   int64 
 9    luxury_assets_value       4269 non-null   int64 
 10   bank_asset_value          4269 non-null   int64 
 11   loan_status               4269 non-null   object
dtypes: int64(9), object(3)
memory usage: 400.3+ KB


In [33]:
df.head()

no_of_dependents      education  self_employed   income_annum  \
0                  2       Graduate             No        9600000   
1                  0   Not Graduate            Yes        4100000   
2                  3       Graduate             No        9100000   
3                  3       Graduate             No        8200000   
4                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [ ]:

from tkinter import *
from tkinter import messagebox




window = Tk()
window.title("Naive Bayes Model")
def predict():
    d=int(dependent.get())
    e=educ.get()
    s=selfemp.get()
    i=int(inc.get())
    l=int(la.get())
    lt=int(lat.get())
    c=int(ch.get())
    rav=int(resass.get())
    cav=int(comass.get())
    lav=int(luxass.get())
    bav=int(banass.get())
    if(e=="Graduate"):
        e=1
    else:
        e=0
        
    if(s=="Yes"):
        s=1
    else:
        s=0
    inputs=[[d,e,s,i,l,lt,c,rav,cav,lav,bav]]
    prediction = model.predict(inputs)
    if(prediction[0]==0):
        messagebox.showinfo("Prediction", f"The loan is rejected")
    else:
        messagebox.showinfo("Prediction", f"The loan is approved")

input_labels = ['Dependents', 'Education', 'SelfEmployed', 'Income', 'Loan Amount', 'Loan Amount Term', 'Cibil Score', 'Residential Asset Value', 'Commercial Asset Value', 'Luxury Asset Value','Bank Asset Value']
dependent= StringVar()
educ= StringVar()
selfemp=StringVar()
inc= StringVar()
la= StringVar()
lat= StringVar()
ch= StringVar()
resass=StringVar()
comass=StringVar()
luxass=StringVar()
banass= StringVar()



label1 = Label(window, text="Dependents")
label1.grid(row=0, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=dependent)
entry.grid(row=0, column=1, padx=10, pady=5)

label2 = Label(window, text="Education")
label2.grid(row=1, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=educ)
entry.grid(row=1, column=1, padx=10, pady=5)

label3 = Label(window, text="Self Employed")
label3.grid(row=2, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=selfemp)
entry.grid(row=2, column=1, padx=10, pady=5)

label4 = Label(window, text="Income")
label4.grid(row=3, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=inc)
entry.grid(row=3, column=1, padx=10, pady=5)

label5 = Label(window, text="Loan Amount")
label5.grid(row=4, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=la)
entry.grid(row=4, column=1, padx=10, pady=5)

label6 = Label(window, text="Loan Amount Term")
label6.grid(row=5, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=lat)
entry.grid(row=5, column=1, padx=10, pady=5)

label7 = Label(window, text="CIBIL score")
label7.grid(row=6, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=ch)
entry.grid(row=6, column=1, padx=10, pady=5)

label8 = Label(window, text="Resedential Asset Value")
label8.grid(row=7, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=resass)
entry.grid(row=7, column=1, padx=10, pady=5)

label9 = Label(window, text="Commercial Asset Value")
label9.grid(row=8, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=comass)
entry.grid(row=8, column=1, padx=10, pady=5)

label10 = Label(window, text="Luxury Asset Value")
label10.grid(row=9, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=luxass)
entry.grid(row=9, column=1, padx=10, pady=5)

label11 = Label(window, text="Bank Asset Value")
label11.grid(row=10, column=0, padx=10, pady=5)
entry = Entry(window, textvariable=banass)
entry.grid(row=10, column=1, padx=10, pady=5)
        

predict_button = Button(window, text="Predict", command=predict)
predict_button.grid(row=11, column=0, columnspan=2, padx=10, pady=10)


window.mainloop()


In [ ]:
X_test[4]

In [ ]:
model.predict([X_test[4]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)